apiVersion: v1
kind: ConfigMap
metadata:
  name: hypebot-config
  namespace: hypebot
data:
  config.yaml: |
    profile_prefix: "Official hypebot for goingdark.social, automatically boosting top trending posts from selected Mastodon instances:"
    
    # profile fields to fill in
    fields:
      instance: https://goingdark.social
      code: "https://github.com/goingdark-social/hypebot"
      about: "Boosts trending posts from curated instances"
    