apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mastodon-cache-recount-statuses
  name: mastodon-cache-recount-statuses
  namespace: goingdark-social
spec:
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      job-name: mastodon-cache-recount-statuses
  suspend: false
  template:
    metadata:
      labels:
        job-name: mastodon-cache-recount-statuses
      name: mastodon-cache-recount-statuses
    spec:
      restartPolicy: Never
      containers:
      - command:
        - bash
        - -c
        - bin/tootctl cache recount accounts -c 50 --verbose
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              key: elastic
              name: elasticsearch-es-elastic-user
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: database-app
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: database-app
        envFrom:
        - configMapRef:
            name: mastodon-env
        - secretRef:
            name: mastodon-secrets-env
        image: ghcr.io/glitch-soc/mastodon:v4.4.5
        name: cache-recount-accounts
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
            