apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mastodon-cache-recount-acounts
  name: mastodon-cache-recount-acounts
  namespace: goingdark-social
spec:
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      job-name: mastodon-cache-recount-acounts
  suspend: false
  template:
    metadata:
      labels:
        job-name: mastodon-cache-recount-acounts
      name: mastodon-cache-recount-acounts
    spec:
      restartPolicy: Never
      tolerations:
      - key: "autoscaler-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      
      volumes:
        - name: db-ca
          secret:
            secretName: database-cnpg-ca
            defaultMode: 0444
      
      containers:
      - command:
        - bash
        - -c
        - bin/tootctl cache recount accounts -c 50 --verbose
        env:
          # Core Rails environment
          - name: RAILS_ENV
            value: "production"
          - name: NODE_ENV
            value: "production"
          - name: TZ
            value: "Europe/Stockholm"
          - name: SINGLE_USER_MODE
            value: "false"
          - name: MASTODON_USE_LIBVIPS
            value: "true"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          
          # Job-specific configuration
          - name: DB_POOL
            value: "1"
          - name: PREPARED_STATEMENTS
            value: "false"
          
          # Database configuration
          - name: DB_HOST
            value: "database-cnpg-pooler-rw"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "mastodon"
          - name: DB_SSLMODE
            value: "verify-ca"
          - name: PGSSLROOTCERT
            value: "/etc/ssl/certs/postgresql/ca.crt"
          - name: DATABASE_TIMEOUT
            value: "60"
          
          # Database credentials from secrets
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-cnpg-app
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: database-cnpg-app
                key: password
          
          # Redis configuration
          - name: REDIS_HOST
            value: "mastodon-redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_URL
            value: "redis://mastodon-redis-master:6379/0"
          - name: SIDEKIQ_REDIS_URL
            value: "redis://mastodon-redis-master:6379/1"
          - name: CACHE_REDIS_URL
            value: "redis://mastodon-redis-master:6379/2"
          
          # Features configuration
          - name: MAX_TOOT_CHARS
            value: "1500"
          - name: DEFAULT_LOCALE
            value: "en"
          - name: FORCE_DEFAULT_LOCALE
            value: "true"
        
        envFrom:
          # Application secrets only
          - secretRef:
              name: mastodon-app-secrets
          - secretRef:
              name: mastodon-db-url
        
        image: ghcr.io/glitch-soc/mastodon:v4.5.0-beta.2
        name: cache-recount-accounts
        
        volumeMounts:
          - name: db-ca
            mountPath: /etc/ssl/certs/postgresql
            readOnly: true
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
            