apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-onion-keygen
  namespace: mastodon
  labels:
    app: mastodon-onion
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: mastodon-onion
    spec:
      restartPolicy: Never
      tolerations:
        - key: autoscaler-node
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: keygen
          image: goldy/tor-hidden-service:v0.4.7.12-54c0e54
          command: ["/bin/sh","-c"]
          args:
            - |
              set -euo pipefail
              mkdir -p /var/lib/tor/hidden_service
              cat >/tmp/torrc <<'EOF'
              HiddenServiceDir /var/lib/tor/hidden_service
              HiddenServicePort 80 127.0.0.1:80
              EOF

              tor -f /tmp/torrc &
              TORPID=$!

              # wait up to 30s for Tor to create the hostname
              i=0
              while [ ! -f /var/lib/tor/hidden_service/hostname ] && [ $i -lt 30 ]; do
                sleep 1
                i=$((i+1))
              done

              if [ -f /var/lib/tor/hidden_service/hostname ]; then
                echo "Onion hostname created:"
                cat /var/lib/tor/hidden_service/hostname || true
                echo "Files:"
                ls -la /var/lib/tor/hidden_service || true
              else
                echo "ERROR: hostname not created within timeout"
                ls -la /var/lib/tor || true
                exit 2
              fi

              kill $TORPID || true
          volumeMounts:
            - name: onion-data
              mountPath: /var/lib/tor/hidden_service

      volumes:
        - name: onion-data
          persistentVolumeClaim:
            claimName: mastodon-onion
