apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-db-migrate
  namespace: mastodon
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: "autoscaler-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
        - name: migrate
          image: ghcr.io/glitch-soc/mastodon:v4.4.4
          command: ["/bin/bash", "-c", "RAILS_ENV=production DB_PORT=5432 bundle exec rails db:migrate --trace"]
          envFrom:
            # Application secrets (domain, keys, credentials)
            - secretRef:
                name: mastodon-app-secrets
            # Database connection credentials
            - secretRef:
                name: mastodon-db-url
            # Core application settings
            - configMapRef:
                name: mastodon-core
            # Database connection details
            - configMapRef:
                name: mastodon-database
            # Job-specific database settings (reduced pool size)
            - configMapRef:
                name: mastodon-jobs
          volumeMounts:
            - name: db-ca
              mountPath: /opt/mastodon/.postgresql/root.crt
              subPath: ca.crt
      volumes:
        - name: db-ca
          secret:
            secretName: mastodon-postgresql-ca
            items:
              - key: ca.crt
                path: ca.crt
