apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-db-migrate
  namespace: mastodon
  annotations:
    kustomize.config.k8s.io/description: |
      Database migration job with static configuration.
      No longer depends on configMapGenerator to avoid hash-suffix issues.
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: "autoscaler-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
        - name: migrate
          image: ghcr.io/glitch-soc/mastodon:v4.4.5
          command: ["/bin/bash", "-c", "RAILS_ENV=production DB_PORT=5432 bundle exec rails db:migrate --trace"]
          env:
            # Essential Rails environment
            - name: RAILS_ENV
              value: "production"
            - name: DB_PORT
              value: "5432"
            # Database connection pool (optimized for migration jobs)
            - name: DB_POOL
              value: "1"
            - name: PREPARED_STATEMENTS
              value: "false"
            # Database connection
            - name: DB_HOST
              value: "mastodon-postgresql-pooler"
            - name: DB_NAME
              value: "mastodon"
            - name: DB_SSLMODE
              value: "require"
            - name: DB_SSLROOTCERT
              value: "/opt/mastodon/.postgresql/root.crt"
            - name: DATABASE_TIMEOUT
              value: "60"
          envFrom:
            # Database credentials (essential)
            - secretRef:
                name: mastodon-db-url
            # Application secrets (needed for some migrations)
            - secretRef:
                name: mastodon-app-secrets
          volumeMounts:
            - name: db-ca
              mountPath: /opt/mastodon/.postgresql/root.crt
              subPath: ca.crt
      volumes:
        - name: db-ca
          secret:
            secretName: mastodon-postgresql-ca
            items:
              - key: ca.crt
                path: ca.crt
