apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mastodon-search-deploy
  name: mastodon-search-deploy
  namespace: mastodon
spec:
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      job-name: mastodon-search-deploy
  suspend: false
  template:
    metadata:
      labels:
        job-name: mastodon-search-deploy
      name: mastodon-search-deploy
    spec:
      restartPolicy: Never
      tolerations:
      - key: "autoscaler-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - command:
        - bash
        - -c
        - bin/tootctl search deploy --concurrency 4 --batch_size 1024
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              key: elastic
              name: elasticsearch-es-elastic-user
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: database-cnpg-app
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: database-cnpg-app
        envFrom:
        - secretRef:
            name: mastodon-app-secrets
        - secretRef:
            name: mastodon-db-url
        - configMapRef:
            name: mastodon-core
        - configMapRef:
            name: mastodon-database
        - configMapRef:
            name: mastodon-redis
        - configMapRef:
            name: mastodon-search
        - configMapRef:
            name: mastodon-features
        - configMapRef:
            name: mastodon-external-services
        - configMapRef:
            name: mastodon-jobs
        image: ghcr.io/glitch-soc/mastodon:v4.4.5
        imagePullPolicy: IfNotPresent
        name: search-deploy
        resources:
          limits:
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 2Gi
        volumeMounts:
        - name: db-ca
          mountPath: /etc/ssl/certs/postgresql
          readOnly: true
      volumes:
      - name: db-ca
        secret:
          secretName: database-cnpg-ca
          defaultMode: 0444