apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-search-deploy
  namespace: mastodon
spec:
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: "autoscaler-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

      volumes:
        - name: db-ca
          secret:
            secretName: database-cnpg-ca
            defaultMode: 0444
        - name: es-ca
          secret:
            secretName: mastodon-elastic-ca
            defaultMode: 0444

      containers:
      - name: search-deploy
        image: ghcr.io/glitch-soc/mastodon:v4.5.0-beta.2
        imagePullPolicy: IfNotPresent

        command: ["/bin/bash","-lc"]
        args:
          - >
            export RAILS_LOG_LEVEL=debug VERBOSE=true;
            stdbuf -oL -eL bin/tootctl search deploy --concurrency 4 --batch_size 1024
            2>&1 | stdbuf -oL tr '\r' '\n'

        env:
          # Core Rails environment
          - name: RAILS_ENV
            value: "production"
          - name: NODE_ENV
            value: "production"
          - name: TZ
            value: "Europe/Stockholm"
          - name: SINGLE_USER_MODE
            value: "false"
          - name: MASTODON_USE_LIBVIPS
            value: "true"
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          
          # Job-specific configuration
          - name: DB_POOL
            value: "1"
          - name: PREPARED_STATEMENTS
            value: "false"
          
          # Database configuration
          - name: DB_HOST
            value: "database-cnpg-pooler-rw"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "mastodon"
          - name: DB_SSLMODE
            value: "verify-ca"
          - name: PGSSLROOTCERT
            value: "/etc/ssl/certs/postgresql/ca.crt"
          - name: DATABASE_TIMEOUT
            value: "60"
          - name: REPLICA_DB_HOST
            value: "database-cnpg-pooler-ro"
          - name: REPLICA_DB_PORT
            value: "5432"
          - name: REPLICA_DB_NAME
            value: "mastodon"
          - name: REPLICA_PREPARED_STATEMENTS
            value: "false"
          - name: REPLICA_DB_TASKS
            value: "false"
          - name: STREAMING_DATABASE_TIMEOUT
            value: "10"
          
          # Database credentials from secrets
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: database-cnpg-app
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: database-cnpg-app
                key: password
          
          # Redis configuration
          - name: REDIS_HOST
            value: "mastodon-redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_URL
            value: "redis://mastodon-redis-master:6379/0"
          - name: SIDEKIQ_REDIS_URL
            value: "redis://mastodon-redis-master:6379/1"
          - name: CACHE_REDIS_URL
            value: "redis://mastodon-redis-master:6379/2"
          - name: STREAMING_REDIS_URL
            value: "redis://mastodon-redis-master:6379/3"
          - name: QUERY_CACHE_REDIS_URL
            value: "redis://mastodon-redis-master:6379/4"
          
          # Elasticsearch configuration
          - name: ES_ENABLED
            value: "true"
          - name: ES_HOST
            value: "https://elasticsearch-es-http"
          - name: ES_PORT
            value: "9200"
          - name: ES_USER
            value: "elastic"
          - name: ES_PRESET
            value: "single_node_cluster"
          - name: ES_SSL
            value: "true"
          - name: SSL_CERT_FILE
            value: "/opt/mastodon/.elasticsearch/ca.crt"
          - name: ES_PASS
            valueFrom:
              secretKeyRef:
                name: elasticsearch-es-elastic-user
                key: elastic
          
          # Features configuration
          - name: MAX_TOOT_CHARS
            value: "1500"
          - name: FETCH_REPLIES_ENABLED
            value: "true"
          - name: FETCH_REPLIES_COOLDOWN_MINUTES
            value: "15"
          - name: FETCH_REPLIES_INITIAL_WAIT_MINUTES
            value: "5"
          - name: FETCH_REPLIES_MAX_GLOBAL
            value: "1000"
          - name: FETCH_REPLIES_MAX_SINGLE
            value: "500"
          - name: FETCH_REPLIES_MAX_PAGES
            value: "500"
          - name: IP_RETENTION_PERIOD
            value: "15552000"
          - name: DEFAULT_LOCALE
            value: "en"
          - name: FORCE_DEFAULT_LOCALE
            value: "true"
          
          # Proxy configuration - explicitly disable for internal services
          - name: HTTP_PROXY
            value: ""
          - name: http_proxy
            value: ""
          - name: HTTPS_PROXY
            value: ""
          - name: https_proxy
            value: ""
          - name: NO_PROXY
            value: "elasticsearch-es-http,elasticsearch-es-internal-http,elasticsearch-es-default,elasticsearch-es-http.mastodon.svc,elasticsearch-es-internal-http.mastodon.svc,.svc,.cluster.local,10.0.0.0/8,127.0.0.1,localhost"
          - name: no_proxy
            value: "elasticsearch-es-http,elasticsearch-es-internal-http,elasticsearch-es-default,elasticsearch-es-http.mastodon.svc,elasticsearch-es-internal-http.mastodon.svc,.svc,.cluster.local,10.0.0.0/8,127.0.0.1,localhost"

        envFrom:
          # Application secrets only
          - secretRef:
              name: mastodon-app-secrets
          - secretRef:
              name: mastodon-db-url

        volumeMounts:
          - name: db-ca
            mountPath: /etc/ssl/certs/postgresql
            readOnly: true
          - name: es-ca
            mountPath: /opt/mastodon/.elasticsearch/ca.crt
            subPath: ca.crt
            readOnly: true

        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            memory: 3Gi
