apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sidekiq-default-pdb.yaml
- sidekiq-federation-pdb.yaml
- sidekiq-background-pdb.yaml
- sidekiq-scheduler-pdb.yaml
- streaming-pdb.yaml
- web-pdb.yaml
