apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

configMapGenerator:
  # Core application config - used by web, sidekiq, streaming
  - name: mastodon-core
    envs:
      - configs/mastodon-core.env

  # Database config - UPDATED FOR CNPG - used by web, sidekiq, jobs
  - name: mastodon-database
    envs:
      - configs/mastodon-database-cnpg.env

  # Redis config - used by web, sidekiq, streaming
  - name: mastodon-redis
    envs:
      - configs/mastodon-redis.env

  # Search config - used by web, sidekiq (when ES enabled)
  - name: mastodon-search
    envs:
      - configs/mastodon-search.env

  # Features and content settings - used by web, sidekiq
  - name: mastodon-features
    envs:
      - configs/mastodon-features.env

  # External services (SMTP + Storage) - used by web, sidekiq
  - name: mastodon-external-services
    envs:
      - configs/mastodon-smtp.env
      - configs/mastodon-storage.env

  # Web-specific config - only web deployment
  - name: mastodon-web
    envs:
      - configs/mastodon-web.env

  # Sidekiq-specific config - only sidekiq
  - name: mastodon-sidekiq
    envs:
      - configs/mastodon-sidekiq.env

  # Streaming-specific config - only streaming
  - name: mastodon-streaming
    envs:
      - configs/mastodon-streaming.env

  # Job-specific config - only for jobs
  - name: mastodon-jobs
    envs:
      - configs/mastodon-jobs.env


  # Configurations
resources:
- namespace.yaml
- configs/
- resources/

patches:
- path: patches/priority-patches.yaml
- path: patches/spread-patches.yaml
- path: patches/cnpg-ca-patches.yaml