apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: mastodon-cache-recount-acounts
  name: mastodon-cache-recount-accounts
spec:
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      job-name: mastodon-cache-recount-acounts
  suspend: false
  template:
    metadata:
      labels:
        job-name: mastodon-cache-recount-acounts
      name: mastodon-cache-recount-acounts
    spec:
      restartPolicy: Never
      containers:
      - name: cache-recount-accounts
        image: ghcr.io/mastodon/mastodon:v4.4.0-beta.1@sha256:49d58b37ff8a1e282e6bef2eae2ea9e0c1d7f39dc62d7e2595b06949fec25c4d
        command:
        - bash
        - -c
        - bin/tootctl cache recount accounts -c 50 --verbose
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-app
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-app
              key: password
        envFrom:
        - configMapRef:
            name: mastodon-core-env
        - secretRef:
            name: mastodon-secrets-env
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
            