apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mastodon-sidekiq-federation-hpa
  namespace: mastodon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mastodon-sidekiq-federation
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: External
      external:
        metric:
          name: sidekiq_queue_latency_seconds
          selector:
            matchLabels:
              queue: "push"
        target:
          type: Value
          value: "30"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
        - type: Pods
          value: 1
          periodSeconds: 45
    scaleDown:
      stabilizationWindowSeconds: 600
