apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mastodon-web-hpa
  namespace: mastodon
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: |
      Primary metric: puma_request_backlog scales on actual request queue depth (leading indicator)
      Target: 3 requests maximum in backlog for responsive performance  
      Safety net: Memory utilization as Ruby apps are memory-bound, not CPU-bound
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mastodon-web
  minReplicas: 2
  maxReplicas: 8
  metrics:
    # Primary scaling metric - request backlog (leading indicator)
    - type: External
      external:
        metric:
          name: puma_request_backlog
          selector:
            matchLabels:
              job: mastodon-web
        target:
          type: Value
          value: "3"   # Scale when > 3 requests waiting
    # Safety net - memory is more predictive than CPU for Ruby apps
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
