apiVersion: apps/v1
kind: Deployment
metadata:
  name: PLACEHOLDER
  labels:
    app: PLACEHOLDER
    component: PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PLACEHOLDER
  template:
    metadata:
      labels:
        app: PLACEHOLDER
        component: PLACEHOLDER
    spec:
      securityContext:
        fsGroup: 991
        fsGroupChangePolicy: Always
      tolerations:
        - key: "autoscaler-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: mastodon
          image: ghcr.io/glitch-soc/mastodon:v4.4.4
          securityContext:
            runAsNonRoot: true
            runAsUser: 991
            runAsGroup: 991
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: mastodon-app-secrets
            - secretRef:
                name: mastodon-db-url
            - configMapRef:
                name: mastodon-core-env
            - configMapRef:
                name: mastodon-db-env
            - configMapRef:
                name: mastodon-cache-env
            - configMapRef:
                name: mastodon-search-env
            - configMapRef:
                name: mastodon-metrics-env
            - configMapRef:
                name: mastodon-features-env
            - configMapRef:
                name: mastodon-storage-env
            - configMapRef:
                name: mastodon-smtp-env
          env:
            - name: DB_SSLMODE
              value: verify-ca
            - name: DB_SSLROOTCERT
              value: /opt/mastodon/.postgresql/root.crt
          volumeMounts:
            - name: db-ca
              mountPath: /opt/mastodon/.postgresql/root.crt
              subPath: ca.crt
            - name: es-ca
              mountPath: /opt/mastodon/.elasticsearch/ca.crt
              subPath: ca.crt
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "512Mi"
      volumes:
        - name: db-ca
          secret:
            secretName: mastodon-postgresql-ca
            items:
              - key: ca.crt
                path: ca.crt
        - name: es-ca
          secret:
            secretName: mastodon-elastic-ca
            items:
              - key: ca.crt
                path: ca.crt