apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: PLACEHOLDER-hpa
  labels:
    app: PLACEHOLDER
    component: PLACEHOLDER
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: PLACEHOLDER
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120