apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml

replacements:
- source:
    kind: Deployment
    name: PLACEHOLDER
    fieldPath: metadata.name
  targets:
  - select:
      kind: Service
    fieldPaths: 
    - spec.selector.app
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths: 
    - spec.scaleTargetRef.name
  - select:
      kind: PodDisruptionBudget
    fieldPaths: 
    - spec.selector.matchLabels.app

- source:
    kind: Deployment
    name: PLACEHOLDER
    fieldPath: metadata.labels.component
  targets:
  - select:
      kind: Service
    fieldPaths: 
    - metadata.labels.component
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths: 
    - metadata.labels.component
  - select:
      kind: PodDisruptionBudget
    fieldPaths: 
    - metadata.labels.component