apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component

resources:
- deployment.yaml
- service.yaml
- hpa.yaml
- pdb.yaml

# Component-local settings: generate a small ConfigMap that holds the SERVICE_NAME
configMapGenerator:
  - name: component-settings
    literals:
      - SERVICE_NAME=mastodon-web

# Use replacements to propagate the configured SERVICE_NAME into the resources
replacements:
- source:
    kind: ConfigMap
    name: component-settings
    fieldPath: data.SERVICE_NAME
  targets:
  - select:
      kind: Service
    fieldPaths:
    - spec.selector.app
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.scaleTargetRef.name
  - select:
      kind: PodDisruptionBudget
    fieldPaths:
    - spec.selector.matchLabels.app

- source:
    kind: ConfigMap
    name: component-settings
    fieldPath: data.SERVICE_NAME
  targets:
  - select:
      kind: Service
    fieldPaths:
    - metadata.labels.component
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - metadata.labels.component
  - select:
      kind: PodDisruptionBudget
    fieldPaths:
    - metadata.labels.component