apiVersion: v1
kind: Service
metadata:
  name: PLACEHOLDER
  labels:
    app: PLACEHOLDER
    component: PLACEHOLDER
spec:
  selector:
    app: PLACEHOLDER
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP