apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc-client
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-backend
  target:
    name: argocd-secret
    creationPolicy: Merge
    template:
      type: Opaque
  data:
    - secretKey: oidc.clientSecret
      remoteRef:
        key: static-client-argocd-secret
