apiVersion: v1
kind: ResourceQuota
metadata:
  name: argocd-resource-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "2Gi"
    pods: "10"
    persistentvolumeclaims: "5"