apiVersion: v1
kind: ResourceQuota
metadata:
  name: argocd-resource-quota
  namespace: argocd
spec:
  hard:
    requests.cpu: "600m"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    pods: "15"
    persistentvolumeclaims: "5"
