apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-scheduler
  namespace: mastodon
  labels:
    app: mastodon-sidekiq-scheduler
    queue-type: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-sidekiq-scheduler
  template:
    metadata:
      labels:
        app: mastodon-sidekiq-scheduler
        queue-type: scheduler
        elasticsearch-client: "true"
    spec:
      securityContext:
        fsGroup: 991
        fsGroupChangePolicy: Always
      tolerations:
        - key: "autoscaler-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: sidekiq-scheduler
          image: ghcr.io/glitch-soc/mastodon
          args:
            - bundle
            - exec
            - sidekiq
            - -q
            - scheduler
            - -c
            - "5"
          envFrom:
            - secretRef:
                name: mastodon-app-secrets
            - secretRef:
                name: mastodon-db-url
            - configMapRef:
                name: mastodon-core
            - configMapRef:
                name: mastodon-database
            - configMapRef:
                name: mastodon-redis
            - configMapRef:
                name: mastodon-search
            - configMapRef:
                name: mastodon-features
            - configMapRef:
                name: mastodon-external-services
            - configMapRef:
                name: mastodon-sidekiq
          env:
            - name: DB_POOL
              value: "5"
          volumeMounts:
            - name: db-ca
              mountPath: /etc/ssl/certs/postgresql
              readOnly: true
            - name: es-ca
              mountPath: /opt/mastodon/.elasticsearch/ca.crt
              subPath: ca.crt
              readOnly: true
          livenessProbe:
            exec:
              command: ["sh", "-c", "ps aux | grep '[s]idekiq\\ 8'"]
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              memory: "500Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 991
            runAsGroup: 991
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: db-ca
          secret:
            secretName: database-cnpg-ca
            defaultMode: 0444
        - name: es-ca
          secret:
            secretName: mastodon-elastic-ca
            defaultMode: 0444
