apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

# Include all base components
resources:
- ../../base
- ../../infrastructure
- ../../services
- ../../networking
- ../../jobs
- priorities.yaml

# Apply production scaling overrides
patches:
- target:
    kind: Deployment
    name: mastodon-web
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3

- target:
    kind: HorizontalPodAutoscaler
    name: mastodon-web-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 3
    - op: replace
      path: /spec/maxReplicas
      value: 10

- target:
    kind: Deployment
    name: mastodon-sidekiq-generic
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5

- target:
    kind: HorizontalPodAutoscaler
    name: mastodon-sidekiq-generic-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 5
    - op: replace
      path: /spec/maxReplicas
      value: 15

- target:
    kind: Deployment
    name: mastodon-streaming
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

- target:
    kind: HorizontalPodAutoscaler
    name: mastodon-streaming-hpa
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 2
    - op: replace
      path: /spec/maxReplicas
      value: 6

labels:
- pairs:
    app.kubernetes.io/part-of: mastodon
    environment: production