apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-credentials
  namespace: victoriametrics
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: grafana
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "{{ .static_client_secret }}"
  data:
    - secretKey: static_client_secret
      remoteRef:
        key: static-client-grafana-secret
