apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - streaming-deployment.yaml
  - svc-streaming.yaml
  - streaming-hpa.yaml
  - streaming-pdb.yaml

patches:
- path: streaming-priority-patch.yaml
