apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-onion-import
  namespace: mastodon
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: SecretStore
  target:
    name: mastodon-onion-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mastodon-onion-bitwarden-name-or-uuid
