apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database-s3-externalsecret.yaml
- db-secrets.yaml
- elastic-secret.yaml
- elastic-serviceaccount.yaml
- es-cert.yaml
- externalsecret.yaml
- psql-secret.yaml
- redis-serviceaccount.yaml
- secretstore.yaml
- serviceaccount.yaml
- walg-externalsecret.yaml
- externalsecret-onion-secrets.yaml
