apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-secrets.yaml
- elastic-secret.yaml
- elastic-serviceaccount.yaml
- es-cert.yaml
- externalsecret.yaml
- mastodon-app-secrets-placeholder.yaml
- mastodon-postgresql-ca.yaml
- postgresql-server-cert.yaml
- psql-secret.yaml
- redis-serviceaccount.yaml
- secretstore.yaml
- serviceaccount.yaml
- walg-externalsecret.yaml
