apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-secrets.yaml
- elastic-secret.yaml
- elastic-serviceaccount.yaml
- es-cert.yaml
- externalsecret.yaml
# TODO: After migration complete and stable (7+ days), remove these Zalando-specific secrets:
# Remove: mastodon-postgresql-ca.yaml, postgresql-server-cert.yaml, psql-secret.yaml, walg-externalsecret.yaml
- mastodon-postgresql-ca.yaml      # Zalando PostgreSQL CA cert - remove after migration
- postgresql-server-cert.yaml      # Zalando PostgreSQL server cert - remove after migration
- psql-secret.yaml                 # Zalando PostgreSQL credentials - remove after migration
- redis-serviceaccount.yaml
- secretstore.yaml
- serviceaccount.yaml
- walg-externalsecret.yaml         # Zalando WAL-G backup credentials - remove after migration
