apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-secrets.yaml
- elastic-secret.yaml
- elastic-serviceaccount.yaml
- es-cert.yaml
- externalsecret.yaml
- redis-serviceaccount.yaml
- secretstore.yaml
- serviceaccount.yaml
