apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mastodon-postgresql-server
  namespace: mastodon
spec:
  secretName: mastodon-postgresql-server
  issuerRef:
    name: internal-issuer
    kind: ClusterIssuer
  commonName: mastodon-postgresql.mastodon.svc
  dnsNames:
    - mastodon-postgresql.mastodon.svc
    - mastodon-postgresql
    - mastodon-postgresql.mastodon.svc.cluster.local
    - mastodon-postgresql-pooler
    - mastodon-postgresql-pooler.mastodon.svc
    - database-cnpg
    - database-cnpg.mastodon.svc
    - database-cnpg.mastodon.svc.cluster.local
    - database-cnpg-rw
    - database-cnpg-rw.mastodon.svc
    - database-cnpg-rw.mastodon.svc.cluster.local
    - database-cnpg-ro
    - database-cnpg-ro.mastodon.svc
    - database-cnpg-ro.mastodon.svc.cluster.local
    - database-cnpg-pooler-rw
    - database-cnpg-pooler-rw.mastodon.svc
    - database-cnpg-pooler-rw.mastodon.svc.cluster.local
    - database-cnpg-pooler-ro
    - database-cnpg-pooler-ro.mastodon.svc
    - database-cnpg-pooler-ro.mastodon.svc.cluster.local
  duration: 2160h       # 90 days
  renewBefore: 360h     # renew 15 days before expiry
  usages:
    - digital signature
    - key encipherment
    - server auth
