apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zalando-standby-credentials
  namespace: mastodon
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: zalando-k8s-store
  target:
    name: zalando-standby-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: standby.mastodon-postgresql.credentials.postgresql.acid.zalan.do
        property: username
    - secretKey: password
      remoteRef:
        key: standby.mastodon-postgresql.credentials.postgresql.acid.zalan.do
        property: password
