apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: database
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/goingdark-social/IaC'
  destinations:
    - namespace: 'database'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
