# ExternalSecret referencing CNPG app user credentials
# Pulls username and password from database-cnpg-app secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mastodon-db-url
  namespace: mastodon
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: cnpg-k8s-store
  target:
    name: mastodon-db-url
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        DB_USER: "{{ .username }}"
        DB_PASS: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: database-cnpg-app
        property: username
    - secretKey: password
      remoteRef:
        key: database-cnpg-app
        property: password
