apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

resources:
- namespace.yaml
- secrets.yaml
- config.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: mastodon