apiVersion: v1
kind: ServiceAccount
metadata:
  name: mastodon-eso-reader
  namespace: mastodon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-role
  namespace: mastodon
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["selfsubjectrulesreviews"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-store-rolebinding
  namespace: mastodon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-store-role
subjects:
- kind: ServiceAccount
  name: mastodon-eso-reader
  namespace: mastodon
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mastodon-bitwarden-store
  namespace: mastodon
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: credentials
            name: bitwarden-cli
            namespace: external-secrets
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      organizationID: 2b3e3e9e-73bc-4c1f-a4c3-b1bd016dc84b
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon-app-secrets
  namespace: mastodon
spec:
  secretStoreRef:
    name: mastodon-bitwarden-store
    kind: SecretStore
  target:
    name: mastodon-app-secrets
    creationPolicy: Owner
  data:
  - secretKey: SECRET_KEY_BASE
    remoteRef:
      key: ffe44e53-aaeb-488a-8e60-b1bf01721a3c
  - secretKey: OTP_SECRET
    remoteRef:
      key: 04b13f2a-fdb0-4f39-b74c-b1bf01721b07
  - secretKey: VAPID_PRIVATE_KEY
    remoteRef:
      key: b93e1b15-7c89-43d7-b47b-b1bf01721b7c
  - secretKey: VAPID_PUBLIC_KEY
    remoteRef:
      key: ce26cee8-2c9a-43ba-a7ae-b1bf01721bbf
  - secretKey: LOCAL_DOMAIN
    remoteRef:
      key: 5e5d7f8e-d8c0-48cf-a8b7-b1bf01721c0e
  - secretKey: WEB_DOMAIN
    remoteRef:
      key: 5e5d7f8e-d8c0-48cf-a8b7-b1bf01721c0e
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: c4c53afe-a6cd-423e-98c5-b1bf01721c5e
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: 7e3bfc5a-b3b8-4a8a-9e83-b1bf01721ca9
  - secretKey: S3_ENDPOINT
    remoteRef:
      key: 0fb95336-9a30-485b-85e4-b1bf01721cf3
  - secretKey: SMTP_SERVER
    remoteRef:
      key: 8a6b0e2f-7e4c-4c5b-b3a0-b1bf01721d3a
  - secretKey: SMTP_PORT
    remoteRef:
      key: ea6a8b66-e5de-483c-b8c3-b1bf01721d83
  - secretKey: SMTP_LOGIN
    remoteRef:
      key: 5b1ee5d0-6b9e-4a19-a8b5-b1bf01721dcc
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: 90cbb81b-0c54-4c5a-9e65-b1bf01721e14
  - secretKey: SMTP_FROM_ADDRESS
    remoteRef:
      key: 89de0b59-8c9a-4b6e-a4c2-b1bf01721e5c
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mastodon-db-url
  namespace: mastodon
spec:
  secretStoreRef:
    name: mastodon-bitwarden-store
    kind: SecretStore
  target:
    name: mastodon-db-url
    creationPolicy: Owner
  data:
  - secretKey: DATABASE_URL
    remoteRef:
      key: fa7b3b4a-0b2e-4c5e-9d85-b1bf01721ea6