apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-onion
  namespace: mastodon
spec:
  parentRefs:
    - name: external
      namespace: gateway
      sectionName: http-onion
  rules:
    - matches:
        - headers:
            - name: Host
              type: RegularExpression
              value: .+\\.onion
          path:
            type: PathPrefix
            value: /api/v1/streaming
      backendRefs:
        - name: mastodon-streaming
          port: 4000
    - matches:
        - headers:
            - name: Host
              type: RegularExpression
              value: .+\\.onion
          path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mastodon-web
          port: 3000
