apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-onion
  namespace: mastodon
spec:
  parentRefs:
    - name: external
      namespace: gateway
      sectionName: http-onion
  hostnames:
    - placeholder.onion
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/streaming
      backendRefs:
        - name: mastodon-streaming
          port: 4000
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Onion-Location
                value: http://placeholder.onion
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: mastodon-web
          port: 3000
      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Onion-Location
                value: http://placeholder.onion
