# All Mastodon networking resources in one file
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-web
  namespace: mastodon
  labels:
    app.kubernetes.io/part-of: mastodon
spec:
  parentRefs:
  - name: public-gateway
    namespace: gateway
  hostnames:
  - goingdark.social
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/streaming
    backendRefs:
    - name: mastodon-streaming
      port: 80
  - backendRefs:
    - name: mastodon-web
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mastodon-api
  namespace: mastodon
  labels:
    app.kubernetes.io/part-of: mastodon
spec:
  parentRefs:
  - name: public-gateway
    namespace: gateway
  hostnames:
  - api.goingdark.social
  rules:
  - backendRefs:
    - name: mastodon-web
      port: 80