---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-nextcloud
  namespace: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud-aio-nextcloud
          env:
            - name: ADMIN_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-aio-passwords
                  key: NEXTCLOUD_PASSWORD
            - name: POSTGRES_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-aio-passwords
                  key: DATABASE_PASSWORD
            - name: REDIS_HOST_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-aio-passwords
                  key: REDIS_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-database
  namespace: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud-aio-database
          env:
            - name: POSTGRES_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-aio-passwords
                  key: DATABASE_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio-redis
  namespace: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud-aio-redis
          env:
            - name: REDIS_HOST_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: nextcloud-aio-passwords
                  key: REDIS_PASSWORD
