apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

resources:
- postgres.yaml
- redis.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: mastodon
      tier: infrastructure