apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mastodon

resources:
  - migrate-job.yaml
  - svc.yaml
  - web-deployment.yaml
  - web-hpa.yaml
  - web-pdb.yaml

patches:
- path: web-priority-patch.yaml
