apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mastodon-web-hpa
  namespace: mastodon
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mastodon-web
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60    # reduced from 300s for faster response
      policies:
        - type: Pods
          value: 2                      # allow 2 pods per period
          periodSeconds: 15             # every 15s instead of 120s
        - type: Percent
          value: 50                     # or 50% increase per period
          periodSeconds: 15
      selectPolicy: Max                 # choose the more aggressive policy
    scaleDown:
      stabilizationWindowSeconds: 900   # keep conservative 15 min before scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
