apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - resource-quota.yaml
  - prometheus-adapter-deployment.yaml
  - prometheus-adapter-rbac.yaml
  - prometheus-adapter-apiservice.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.59.5
    releaseName: vm
    namespace: observability
    includeCRDs: true
    valuesFile: values.yaml