apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts
    version: 0.33.5
    releaseName: vm
    namespace: observability
    includeCRDs: true
    valuesInline: {}
