apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      labels:
        app: prometheus-adapter
    spec:
      containers:
        - name: prometheus-adapter
          image: quay.io/prometheus/prometheus-adapter:v0.12.0
          args:
            # Updated to use VMSingle service instead of mastodon-prometheus
            - --prometheus-url=http://vm-victoria-metrics-k8s-stack-vmsingle.observability.svc:8429/
            - --metrics-relist-interval=1m
            - --v=4
          ports:
            - containerPort: 6443
              name: https
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      serviceAccountName: prometheus-adapter
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: observability
spec:
  ports:
    - port: 443
      targetPort: https
  selector:
    app: prometheus-adapter