apiVersion: v1
kind: ResourceQuota
metadata:
  name: observability-resource-quota
  namespace: observability
spec:
  hard:
    requests.cpu: "600m"
    requests.memory: "1.5Gi"
    limits.cpu: "2"
    limits.memory: "3Gi"
    pods: "20"
    persistentvolumeclaims: "5"