apiVersion: v1
kind: ResourceQuota
metadata:
  name: observability-resource-quota
  namespace: observability
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "1Gi"
    limits.cpu: "1"
    limits.memory: "2Gi"
    pods: "15"
    persistentvolumeclaims: "5"