# Disable resource-heavy components
grafana:
  enabled: false

# Keep VMAlert enabled but minimal to avoid template bug
vmalert:
  enabled: true
  spec:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

# Keep essential monitoring components  
kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus-node-exporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# Configure VMSingle with minimal settings
vmsingle:
  enabled: true
  spec:
    retentionPeriod: 7d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

# Configure VMAgent with minimal settings
vmagent:
  enabled: true
  spec:
    scrapeInterval: 60s
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
