apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
  namespace: mastodon
spec:
  template:
    spec:
      containers:
        - name: web
          env:
            - name: RAILS_LOG_LEVEL
              value: debug
