apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
  namespace: mastodon
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-streaming
  namespace: mastodon
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-default
  namespace: mastodon
spec:
  replicas: 1
