apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # New multi-worker deployments
  - sidekiq-generic-deployment.yaml
  - sidekiq-scheduler-deployment.yaml
  
  # Updated scaling and disruption policies
  - sidekiq-hpa.yaml
  - sidekiq-generic-pdb.yaml
  - sidekiq-scheduler-pdb.yaml
  
  # Keep VPA if you want it (you might want separate VPAs for each worker type)
  # - sidekiq-vpa.yaml

patches:
# Apply priority class to both worker types
- target:
    group: apps
    version: v1
    kind: Deployment
    name: mastodon-sidekiq-generic
  patch: |-
    - op: add
      path: /spec/template/spec/priorityClassName
      value: mastodon-high

- target:
    group: apps
    version: v1
    kind: Deployment
    name: mastodon-sidekiq-scheduler
  patch: |-
    - op: add
      path: /spec/template/spec/priorityClassName
      value: mastodon-high

# Apply anti-affinity to generic workers for better distribution
- target:
    group: apps
    version: v1
    kind: Deployment
    name: mastodon-sidekiq-generic
  patch: |-
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: mastodon-sidekiq-generic
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: "autoscaler-node"
                operator: NotIn
                values: ["true"]