apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-scheduler
  namespace: mastodon
  labels:
    app: mastodon-sidekiq-scheduler
    component: sidekiq-worker
    app.kubernetes.io/part-of: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-sidekiq-scheduler
  template:
    metadata:
      labels:
        app: mastodon-sidekiq-scheduler
        component: sidekiq-worker
        app.kubernetes.io/part-of: mastodon
        elasticsearch-client: "true"
    spec:
      securityContext:
        fsGroup: 991
        fsGroupChangePolicy: Always
      tolerations:
        - key: "autoscaler-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: sidekiq
          image: ghcr.io/glitch-soc/mastodon:v4.4.4
          args:
            - bundle
            - exec
            - sidekiq
            - -c
            - "25"
            - -q
            - scheduler
          envFrom:
            - secretRef:
                name: mastodon-app-secrets
            - secretRef:
                name: mastodon-db-url
            - configMapRef:
                name: mastodon-core-env
            - configMapRef:
                name: mastodon-db-env
            - configMapRef:
                name: mastodon-cache-env
            - configMapRef:
                name: mastodon-search-env
            - configMapRef:
                name: mastodon-metrics-env
            - configMapRef:
                name: mastodon-features-env
            - configMapRef:
                name: mastodon-storage-env
            - configMapRef:
                name: mastodon-smtp-env
          env:
            - name: DB_SSLMODE
              value: verify-ca
            - name: DB_SSLROOTCERT
              value: /opt/mastodon/.postgresql/root.crt
            - name: DB_POOL
              value: "25"
          volumeMounts:
            - name: db-ca
              mountPath: /opt/mastodon/.postgresql/root.crt
              subPath: ca.crt
            - name: es-ca
              mountPath: /opt/mastodon/.elasticsearch/ca.crt
              subPath: ca.crt
          livenessProbe:
            exec:
              command: ["sh", "-c", "ps aux | grep '[s]idekiq\\ 7'"]
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests:
              cpu: "317m"
              memory: "633Mi"
            limits:
              memory: "633Mi"
          securityContext:
            runAsNonRoot: true
            runAsUser: 991
            runAsGroup: 991
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: db-ca
          secret:
            secretName: mastodon-postgresql-ca
            items:
              - key: ca.crt
                path: ca.crt
        - name: es-ca
          secret:
            secretName: mastodon-elastic-ca
            items:
              - key: ca.crt
                path: ca.crt