apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mastodon-sidekiq-generic-pdb
  namespace: mastodon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mastodon-sidekiq-generic