apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mastodon-sidekiq-scheduler-pdb
  namespace: mastodon
spec:
  minAvailable: 1  # Keep the scheduler worker available
  selector:
    matchLabels:
      app: mastodon-sidekiq-scheduler