apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-tls
  namespace: dex
spec:
  dnsNames:
    - "*idp.goingdark.social"
    - idp.goingdark.social
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-issuer
  secretName: dex-tls
  usages:
    - digital signature
    - key encipherment
