replicaCount: 3

https:
  enabled: true

podDisruptionBudget:
  enabled: true
  minAvailable: 2

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    memory: 100Mi

envFrom:
  - secretRef:
      name: static-client-secrets
  - secretRef:
      name: dex-secrets

volumes:
  - name: dex-tls
    secret:
      secretName: dex-tls

volumeMounts:
  - name: dex-tls
    mountPath: /etc/dex/tls

config:
  issuer: https://idp.goingdark.social
  logger:
    level: info
    format: text
  storage:
    type: kubernetes
    config:
      inCluster: true

  enablePasswordDB: false

  oauth2:
    responseTypes:
      - code
      - id_token
      - token
    skipApprovalScreen: true
    alwaysShowLoginScreen: false
    
  staticClients:
    - id: argocd
      redirectURIs:
        - https://argocd.goingdark.social/auth/callback
        - http://localhost:8085/auth/callback
      name: "ArgoCD"
      secretEnv: STATIC_CLIENT_ARGOCD_SECRET
    - id: grafana
      redirectURIs:
        - https://monitoring.goingdark.social/login/generic_oauth
      name: "Grafana"
      secretEnv: STATIC_CLIENT_GRAFANA_SECRET

  web:
    https: 0.0.0.0:5554
    tlsCert: /etc/dex/tls/tls.crt
    tlsKey: /etc/dex/tls/tls.key
    tlsMinVersion: 1.2
    tlsMaxVersion: 1.3

  connectors:
    - type: oauth
      id: mastodon
      name: Mastodon (goingdark.social)
      config:
        clientID: $MASTODON_CLIENT_ID
        clientSecret: $MASTODON_CLIENT_SECRET
        redirectURI: https://idp.goingdark.social/callback
        authorizationURL: https://goingdark.social/oauth/authorize
        tokenURL: https://goingdark.social/oauth/token
        # Prefer Mastodon's OIDC-style userinfo for a stable 'sub'.
        userInfoURL: https://goingdark.social/oauth/userinfo
        scopes:
          - profile
        # Map fields from userinfo to standard claims Dex emits.
        userIDKey: sub
        claimMapping:
          userNameKey: acct
          preferredUsernameKey: acct
          # Mastodon userinfo lacks email. We don't emit an email.
          # Grafana will synthesize one from preferred_username.

ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: idp.goingdark.social
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dex-tls
      hosts:
        - idp.goingdark.social