apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  apiVersion: external-secrets.io/v1
  kind: ExternalSecret
  metadata:
    name: dex-secrets
    namespace: dex
  spec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: bitwarden-backend
    target:
      name: dex-secrets
      creationPolicy: Merge
    # Mapping style matches other ExternalSecrets in this repo (see argocd example).
    # Assumption: the Bitwarden remote keys are named as below. If your Bitwarden
    # keys differ, replace the `remoteRef.key` values with the correct names/IDs.
    data:
      - secretKey: MASTODON_CLIENT_ID
        remoteRef:
          key: dex-mastodon-client-id
      - secretKey: MASTODON_CLIENT_SECRET
        remoteRef:
          key: dex-mastodon-client-secret
  ---
  apiVersion: external-secrets.io/v1
  kind: ExternalSecret
  metadata:
    name: static-client-secrets
    namespace: dex
  spec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: bitwarden-backend
    target:
      name: static-client-secrets
      creationPolicy: Merge
    # Map static client secrets into env var names referenced by the helm values
    data:
      - secretKey: STATIC_CLIENT_ARGOCD_SECRET
        remoteRef:
          key: static-client-argocd-secret
      - secretKey: STATIC_CLIENT_GRAFANA_SECRET
        remoteRef:
          key: static-client-grafana-secret