apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: nextcloud-password-gen
  namespace: nextcloud
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: database-password-gen
  namespace: nextcloud
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: redis-password-gen
  namespace: nextcloud
spec:
  length: 32
  digits: 8
  symbols: 0
  noUpper: false
  allowRepeat: true
