apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: nextcloud-aio-passwords
  namespace: nextcloud
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: bitwarden-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-aio-passwords
  data:
    - match:
        secretKey: NEXTCLOUD_PASSWORD
        remoteRef:
          remoteKey: app-nextcloud-nextcloud-password
    - match:
        secretKey: DATABASE_PASSWORD
        remoteRef:
          remoteKey: app-nextcloud-database-password
    - match:
        secretKey: REDIS_PASSWORD
        remoteRef:
          remoteKey: app-nextcloud-redis-password
