# https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
cluster:
  name: talos
  id: 1

# Correct boolean, not a nested map
kubeProxyReplacement: true

  # Talos specific
k8sServiceHost: localhost
k8sServicePort: 7445
securityContext:
  capabilities:
    ciliumAgent:
      [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

# https://www.talos.dev/latest/talos-guides/network/host-dns/#forwarding-kube-dns-to-host-dns
# https://docs.cilium.io/en/stable/operations/performance/tuning/#ebpf-host-routing
bpf:
  hostLegacyRouting: true

# https://docs.cilium.io/en/stable/network/concepts/ipam/
ipam:
  mode: kubernetes
  multiPoolPreAllocation: ''

enableMulticast: false
multicast:
  enabled: false


operator:
  rollOutPods: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true
agent: true
agentConfig:
  tolerations:
    - key: gpu
      operator: Equal
      value: "true"
      effect: NoSchedule
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi



#debug:
#  enabled: true

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 20
  burst: 100

l2announcements:
  enabled: true

externalIPs:
  enabled: true

#enableCiliumEndpointSlice: true

loadBalancer:
  # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#maglev-consistent-hashing
  algorithm: maglev

gatewayAPI:
  enabled: true

# Ensure Cilium deploys the Envoy dataplane
envoy:
  enabled: true

hubble:
  peerService:
    clusterDomain: cluster.local
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  ui:
    enabled: true
    rollOutPods: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

# Ingress controller stays disabled; remove unused settings.
ingressController:
  enabled: false

# mTLS
authentication:
  enabled: false
  mutual:
    spire:
      enabled: false
      install:
        server:
          dataStorage:
            storageClass: cilium-spire-sc
