apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  primaryUpdateStrategy: unsupervised
  enablePDB: true

  env:
    - name: AWS_REQUEST_CHECKSUM_CALCULATION
      value: when_required
    - name: AWS_RESPONSE_CHECKSUM_VALIDATION
      value: when_required
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: mastodon-walg-s3
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: mastodon-walg-s3
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: mastodon-walg-s3
          key: AWS_ENDPOINT
    - name: WAL_S3_BUCKET
      valueFrom:
        secretKeyRef:
          name: mastodon-walg-s3
          key: WAL_S3_BUCKET

  storage:
    size: 40Gi
  walStorage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      # statistics
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: "all"
      # Archive configuration matching Zalando setup
      archive_timeout: "300"
      # pgtune
      # DB Version: 17
      # OS Type: linux
      # DB Type: oltp
      # Total Memory (RAM): 2 GB
      # CPUs num: 1
      # Data Storage: san
      max_connections: "300"
      shared_buffers: "512MB"
      effective_cache_size: "512MB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "100"
      work_mem: "1702kB"
      huge_pages: "off"
      min_wal_size: "2GB"
      max_wal_size: "8GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"

  # Bootstrap from Zalando cluster via pg_basebackup
  bootstrap:
    pg_basebackup:
      source: zalando-cluster
      database: mastodon

  # Enable replica mode - streams from Zalando until promoted
  replica:
    enabled: true
    source: zalando-cluster

  # External cluster connection (Zalando PostgreSQL)
  externalClusters:
    - name: zalando-cluster
      connectionParameters:
        host: mastodon-postgresql-rw.mastodon.svc
        user: streaming_replica
        dbname: postgres
        sslmode: verify-full
      password:
        name: zalando-streaming-replica
        key: password
      sslKey:
        name: zalando-replication-tls
        key: tls.key
      sslCert:
        name: zalando-replication-tls
        key: tls.crt
      sslRootCert:
        name: zalando-replication-ca
        key: ca.crt

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: database-backup

  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "2Gi"

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    # Keep Postgres able to run on both normal workers and autoscaler nodes
    tolerations:
      - key: "autoscaler-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"

---
# ScheduledBackup commented out - should only run after promotion to primary
# Uncomment after successfully promoting the CNPG cluster and demoting Zalando
# apiVersion: postgresql.cnpg.io/v1
# kind: ScheduledBackup
# metadata:
#   name: database-backup
# spec:
#   # runs on monday and thursday at 06:00
#   schedule: "0 0 6 * * 1,4"
#   backupOwnerReference: self
#   cluster:
#     name: database
#   method: plugin
#   pluginConfiguration:
#     name: barman-cloud.cloudnative-pg.io
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: database-pooler-rw
spec:
  cluster:
    name: database
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "125"
  template:
    metadata:
      labels:
        app: database-pooler-rw
    spec:
      containers:
        - resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 100Mi
          name: pgbouncer
      tolerations:
        - key: "autoscaler-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - database-pooler-rw
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: database-backup
spec:
  configuration:
    destinationPath: s3://mastovault/cnpg/mastodon-database
    endpointURL: https://s3.jorijn.com
    s3Credentials:
      accessKeyId:
        name: mastodon-walg-s3
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: mastodon-walg-s3
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
    data:
      additionalCommandArgs:
        - --max-archive-size=10GB
        - --min-chunk-size=64MB # default chunk size is 5MB, but Hetzners limit of 10k objects per multi-part object results in a limit of 50GB per backup file (see: https://docs.hetzner.com/storage/object-storage/overview/#limits)
        - --read-timeout=180 # Hetzner S3 can be slow
  retentionPolicy: "14d"
