apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: database-backup
  namespace: mastodon
spec:
  configuration:
    destinationPath: 's3://mastovault/cnpg/mastodon-database'
    # Proxy endpoint - proxy will forward to real R2 URL from secret
    endpointURL: http://r2-proxy.mastodon.svc.cluster.local
    s3Credentials:
      accessKeyId:
        name: mastodon-walg-s3
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: mastodon-walg-s3
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
      maxParallel: 8
    data:
      compression: gzip
      jobs: 2
  retentionPolicy: "14d"
  instanceSidecarConfiguration:
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: "when_required"
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: "when_required"
      - name: AWS_ENDPOINT_URL
        valueFrom:
          secretKeyRef:
            name: s3-endpoint-config
            key: ENDPOINT_URL
      - name: NO_PROXY
        value: "localhost,127.0.0.1,*.svc,cluster.local"
