---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: database-backup
  namespace: mastodon
spec:
  schedule: "0 6 * * 1,4"  # Mondays and Thursdays at 06:00
  backupOwnerReference: self
  cluster:
    name: database-cnpg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
