apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- database-cluster.yaml    # CNPG - ready for migration
- database-rw-pooler.yaml  # CNPG - ready for migration  
- elastic-sts.yaml
- redis-statefulset.yaml
- sidekiq-default-deployment.yaml
- sidekiq-federation-deployment.yaml
- sidekiq-background-deployment.yaml
- sidekiq-scheduler-deployment.yaml
- streaming-deployment.yaml
- web-deployment.yaml
