apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- elastic-sts.yaml
- redis-statefulset.yaml
- sidekiq-deployment.yaml
- streaming-deployment.yaml
- web-deployment.yaml
