apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-onion
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-onion
  template:
    metadata:
      labels:
        app: mastodon-onion
    spec:
      initContainers:
        - name: restore-onion
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              set -e
              mkdir -p /var/lib/tor/hidden_service
              # copy files from secret mount into PVC and fix perms
              if [ -f /secret/hs_ed25519_public_key ]; then
                cp /secret/hs_ed25519_public_key /var/lib/tor/hidden_service/hs_ed25519_public_key
              fi
              if [ -f /secret/hs_ed25519_secret_key ]; then
                cp /secret/hs_ed25519_secret_key /var/lib/tor/hidden_service/hs_ed25519_secret_key
              fi
              if [ -f /secret/hostname ]; then
                cp /secret/hostname /var/lib/tor/hidden_service/hostname
              fi
              chmod 700 /var/lib/tor/hidden_service
              chmod 600 /var/lib/tor/hidden_service/hs_ed25519_secret_key || true
          volumeMounts:
            - name: onion-secret
              mountPath: /secret
              readOnly: true
            - name: onion-data
              mountPath: /var/lib/tor/hidden_service
      containers:
        - name: tor
          image: goldy/tor-hidden-service:v0.4.7.12-54c0e54
          env:
            - name: SERVICE1_TOR_SERVICE_HOSTS
              value: "80:mastodon-web.mastodon.svc.cluster.local:80"
            - name: SERVICE1_TOR_SERVICE_VERSION
              value: "3"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /var/lib/tor/hidden_service/
              name: onion-data
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: onion-secret
          secret:
            secretName: mastodon-onion-keys
        - name: onion-data
          persistentVolumeClaim:
            claimName: mastodon-onion
