apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-onion
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-onion
  template:
    metadata:
      labels:
        app: mastodon-onion
    spec:
      # Init container runs as root to copy key files and set permissions
      initContainers:
        - name: restore-onion
          image: containers.torproject.org/tpo/onion-services/onimages/tor:alpine
          securityContext:
            runAsUser: 0
          command: ["/bin/sh","-ceu"]
          args:
            - |
              set -eux
              mkdir -p /var/lib/tor/hidden_service
              # copy keys in if provided
              [ -f /secret/hs_ed25519_public_key ] && cp /secret/hs_ed25519_public_key /var/lib/tor/hidden_service/hs_ed25519_public_key || true
              [ -f /secret/hs_ed25519_secret_key ] && cp /secret/hs_ed25519_secret_key /var/lib/tor/hidden_service/hs_ed25519_secret_key || true
              [ -f /secret/hostname ] && cp /secret/hostname /var/lib/tor/hidden_service/hostname || true
              # detect the tor user UID inside this image (fallback to 100 if not found)
              UID="$(getent passwd tor 2>/dev/null | awk -F: '{print $3}' || true)"
              [ -z "$UID" ] && UID="$(getent passwd debian-tor 2>/dev/null | awk -F: '{print $3}' || true)"
              [ -z "$UID" ] && UID="100"
              chown -R "${UID}:${UID}" /var/lib/tor/hidden_service
              chmod 700 /var/lib/tor/hidden_service
              [ -f /var/lib/tor/hidden_service/hs_ed25519_secret_key ] && chmod 600 /var/lib/tor/hidden_service/hs_ed25519_secret_key || true
          volumeMounts:
            - name: onion-secret
              mountPath: /secret
              readOnly: true
            - name: onion-data
              mountPath: /var/lib/tor/hidden_service
      containers:
        - name: tor
          # Official Tor Project onion-service image
          image: containers.torproject.org/tpo/onion-services/onimages/tor:alpine
          # Start tor and tell it to use our torrc
          command: ["tor", "-f", "/etc/tor/torrc"]
          ports:
            - containerPort: 80
              name: http
            - containerPort: 4000
              name: streaming
          volumeMounts:
            - mountPath: /var/lib/tor/hidden_service
              name: onion-data
            - name: torrc
              mountPath: /etc/tor/torrc
              subPath: torrc
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: onion-secret
          secret:
            secretName: mastodon-onion-keys
        - name: onion-data
          persistentVolumeClaim:
            claimName: mastodon-onion
        - name: torrc
          configMap:
            name: mastodon-onion-torrc
            items:
              - key: torrc
                path: torrc
