apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-onion
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon-onion
  template:
    metadata:
      labels:
        app: mastodon-onion
    spec:
      containers:
        - name: tor
          image: goldy/tor-hidden-service:v0.4.7.12-54c0e54
          env:
            - name: SERVICE1_TOR_SERVICE_HOSTS
              value: "80:mastodon-web.mastodon.svc.cluster.local:80"
            - name: SERVICE1_TOR_SERVICE_VERSION
              value: "3"
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /var/lib/tor/hidden_service/
              name: onion-data
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
      volumes:
        - name: onion-data
          persistentVolumeClaim:
            claimName: mastodon-onion
