name: Kustomize Nu Validation

on:
  push:
    paths:
      - 'kubernetes/**'
      - '.github/workflows/validate-kustomize.yml'
  pull_request:
    paths:
      - 'kubernetes/**'
      - '.github/workflows/validate-kustomize.yml'

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: omarluq/kustomize-nu-validation@alpha
        with:
          entry: ./kubernetes
