name: Kustomize Nu Validation
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  validate-kustomize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: omarluq/kustomize-nu-validation@alpha
        with:
          entry: ./kubernetes
