name: Validate Kustomize Manifests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'kubernetes/**'
      - '.github/workflows/validate-kustomize.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Validate manifests with Kubeconform
        uses: omarluq/kustomize-nu-validation@alpha
        with:
          entry: ./kubernetes

